### ISSUE TITLE
Docker Image is not correct.

### ISSUE THREAD

**Issue by mark-robustelli** [FusionAuth/fusionauth-quickstart-springboot-web#2]
@rideam , It looks like the icon to login on the docker page is still missing.

**Comment by rideam** [comment]
@mark-robustelli did you run `docker compose down -v` to remove the previous containers that may have been build when you tested before. The kickstart needs to rerun and the lines below that I had removed in the `kickstart/css/style.css` is the one hiding the header which has the lock icon ( I see you reverted the merge )

![CleanShot 2023-09-25 at 20 54 18@2x](https://github.com/FusionAuth/fusionauth-quickstart-springboot-web/assets/31291528/1bbde0b4-9334-4767-8ebb-df2e1c8bbf12)

I can see it on my end 
![CleanShot 2023-09-25 at 21 14 20@2x](https://github.com/FusionAuth/fusionauth-quickstart-springboot-web/assets/31291528/1e03a77f-ae1d-4cdf-a8ac-fd359468ea70)

**Comment by mark-robustelli** [comment]
Thanks.  Tried it again and it appears to be working now.  May have been a caching issue.  Thanks.
